name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - jupyterlab
  - mystmd
  - jupyterlab-myst 
  - sounderpy
  - cartopy
  - matplotlib
  - metpy
  - numpy
  - xarray
  - siphon
  - pandas
  - ipython

 